name: gen
description: A new Flutter package project.
version: 0.0.1
homepage: none

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  # for network model
  vexana: ^5.0.1

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  assets:
    - assets/colors/
    - assets/lottie/
    - assets/icons/
    - assets/images/
